name: movie_api
description: A simple server to manage movies
version: 0.1.0
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  mysql1: ^0.20.0
  json_annotation: ^4.8.0 # برای تبدیل داده‌ها به JSON

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.20.0
